# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 182909bc488a68374eef20c9cd48860c54778ff3883158531045483ab8ae4900b1f764fdf2d1a17b7226e4ae6c47c8567daf605b508c68f9dd7e8e9a82b2ccbd

test:
  secret_key_base: a99fd031e7dc96e69fde8f0a20b37bd45032aa8e9ba45f10afab510c7d13b06fb0417c4557dfe053427a8daffb6ba5d025def40ecea5e1c0597ed8a472fa2a30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
